//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 11:46:28 AM EDT 
//


package org.cvrgrid.gemuse.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AdmitTime"/>
 *         &lt;element ref="{}UnconfirmedReceivedTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "admitTime",
    "unconfirmedReceivedTime"
})
@XmlRootElement(name = "Order")
public class Order {

    @XmlElement(name = "AdmitTime", required = true)
    protected String admitTime;
    @XmlElement(name = "UnconfirmedReceivedTime", required = true)
    protected String unconfirmedReceivedTime;

    /**
     * Gets the value of the admitTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmitTime() {
        return admitTime;
    }

    /**
     * Sets the value of the admitTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmitTime(String value) {
        this.admitTime = value;
    }

    /**
     * Gets the value of the unconfirmedReceivedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnconfirmedReceivedTime() {
        return unconfirmedReceivedTime;
    }

    /**
     * Sets the value of the unconfirmedReceivedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnconfirmedReceivedTime(String value) {
        this.unconfirmedReceivedTime = value;
    }

}
