//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 11:46:28 AM EDT 
//


package org.cvrgrid.gemuse.jaxb.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MuseInfo"/>
 *         &lt;element ref="{}PatientDemographics"/>
 *         &lt;element ref="{}TestDemographics"/>
 *         &lt;element ref="{}Order"/>
 *         &lt;element ref="{}RestingECGMeasurements"/>
 *         &lt;element ref="{}Diagnosis"/>
 *         &lt;element ref="{}MeasurementMatrix"/>
 *         &lt;element ref="{}QRSTimesTypes"/>
 *         &lt;element ref="{}Waveform" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "museInfo",
    "patientDemographics",
    "testDemographics",
    "order",
    "restingECGMeasurements",
    "diagnosis",
    "measurementMatrix",
    "qrsTimesTypes",
    "waveform"
})
@XmlRootElement(name = "RestingECG")
public class RestingECG {

    @XmlElement(name = "MuseInfo", required = true)
    protected MuseInfo museInfo;
    @XmlElement(name = "PatientDemographics", required = true)
    protected PatientDemographics patientDemographics;
    @XmlElement(name = "TestDemographics", required = true)
    protected TestDemographics testDemographics;
    @XmlElement(name = "Order", required = true)
    protected Order order;
    @XmlElement(name = "RestingECGMeasurements", required = true)
    protected RestingECGMeasurements restingECGMeasurements;
    @XmlElement(name = "Diagnosis", required = true)
    protected Diagnosis diagnosis;
    @XmlElement(name = "MeasurementMatrix", required = true)
    protected String measurementMatrix;
    @XmlElement(name = "QRSTimesTypes", required = true)
    protected QRSTimesTypes qrsTimesTypes;
    @XmlElement(name = "Waveform", required = true)
    protected List<Waveform> waveform;

    /**
     * Gets the value of the museInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MuseInfo }
     *     
     */
    public MuseInfo getMuseInfo() {
        return museInfo;
    }

    /**
     * Sets the value of the museInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MuseInfo }
     *     
     */
    public void setMuseInfo(MuseInfo value) {
        this.museInfo = value;
    }

    /**
     * Gets the value of the patientDemographics property.
     * 
     * @return
     *     possible object is
     *     {@link PatientDemographics }
     *     
     */
    public PatientDemographics getPatientDemographics() {
        return patientDemographics;
    }

    /**
     * Sets the value of the patientDemographics property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientDemographics }
     *     
     */
    public void setPatientDemographics(PatientDemographics value) {
        this.patientDemographics = value;
    }

    /**
     * Gets the value of the testDemographics property.
     * 
     * @return
     *     possible object is
     *     {@link TestDemographics }
     *     
     */
    public TestDemographics getTestDemographics() {
        return testDemographics;
    }

    /**
     * Sets the value of the testDemographics property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestDemographics }
     *     
     */
    public void setTestDemographics(TestDemographics value) {
        this.testDemographics = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setOrder(Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the restingECGMeasurements property.
     * 
     * @return
     *     possible object is
     *     {@link RestingECGMeasurements }
     *     
     */
    public RestingECGMeasurements getRestingECGMeasurements() {
        return restingECGMeasurements;
    }

    /**
     * Sets the value of the restingECGMeasurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestingECGMeasurements }
     *     
     */
    public void setRestingECGMeasurements(RestingECGMeasurements value) {
        this.restingECGMeasurements = value;
    }

    /**
     * Gets the value of the diagnosis property.
     * 
     * @return
     *     possible object is
     *     {@link Diagnosis }
     *     
     */
    public Diagnosis getDiagnosis() {
        return diagnosis;
    }

    /**
     * Sets the value of the diagnosis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Diagnosis }
     *     
     */
    public void setDiagnosis(Diagnosis value) {
        this.diagnosis = value;
    }

    /**
     * Gets the value of the measurementMatrix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementMatrix() {
        return measurementMatrix;
    }

    /**
     * Sets the value of the measurementMatrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementMatrix(String value) {
        this.measurementMatrix = value;
    }

    /**
     * Gets the value of the qrsTimesTypes property.
     * 
     * @return
     *     possible object is
     *     {@link QRSTimesTypes }
     *     
     */
    public QRSTimesTypes getQRSTimesTypes() {
        return qrsTimesTypes;
    }

    /**
     * Sets the value of the qrsTimesTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QRSTimesTypes }
     *     
     */
    public void setQRSTimesTypes(QRSTimesTypes value) {
        this.qrsTimesTypes = value;
    }

    /**
     * Gets the value of the waveform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waveform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaveform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Waveform }
     * 
     * 
     */
    public List<Waveform> getWaveform() {
        if (waveform == null) {
            waveform = new ArrayList<Waveform>();
        }
        return this.waveform;
    }

}
