//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 11:46:28 AM EDT 
//


package org.cvrgrid.gemuse.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DataType"/>
 *         &lt;element ref="{}Site"/>
 *         &lt;element ref="{}SiteName"/>
 *         &lt;element ref="{}AcquisitionDevice"/>
 *         &lt;element ref="{}Status"/>
 *         &lt;element ref="{}Priority"/>
 *         &lt;element ref="{}Location"/>
 *         &lt;element ref="{}AcquisitionTime"/>
 *         &lt;element ref="{}AcquisitionDate"/>
 *         &lt;element ref="{}CartNumber"/>
 *         &lt;element ref="{}AcquisitionSoftwareVersion"/>
 *         &lt;element ref="{}AnalysisSoftwareVersion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataType",
    "site",
    "siteName",
    "acquisitionDevice",
    "status",
    "priority",
    "location",
    "acquisitionTime",
    "acquisitionDate",
    "cartNumber",
    "acquisitionSoftwareVersion",
    "analysisSoftwareVersion"
})
@XmlRootElement(name = "TestDemographics")
public class TestDemographics {

    @XmlElement(name = "DataType", required = true)
    protected String dataType;
    @XmlElement(name = "Site", required = true)
    protected String site;
    @XmlElement(name = "SiteName", required = true)
    protected String siteName;
    @XmlElement(name = "AcquisitionDevice", required = true)
    protected String acquisitionDevice;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "Priority", required = true)
    protected String priority;
    @XmlElement(name = "Location", required = true)
    protected String location;
    @XmlElement(name = "AcquisitionTime", required = true)
    protected String acquisitionTime;
    @XmlElement(name = "AcquisitionDate", required = true)
    protected String acquisitionDate;
    @XmlElement(name = "CartNumber", required = true)
    protected String cartNumber;
    @XmlElement(name = "AcquisitionSoftwareVersion", required = true)
    protected String acquisitionSoftwareVersion;
    @XmlElement(name = "AnalysisSoftwareVersion", required = true)
    protected String analysisSoftwareVersion;

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSite(String value) {
        this.site = value;
    }

    /**
     * Gets the value of the siteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * Sets the value of the siteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteName(String value) {
        this.siteName = value;
    }

    /**
     * Gets the value of the acquisitionDevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquisitionDevice() {
        return acquisitionDevice;
    }

    /**
     * Sets the value of the acquisitionDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquisitionDevice(String value) {
        this.acquisitionDevice = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the acquisitionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquisitionTime() {
        return acquisitionTime;
    }

    /**
     * Sets the value of the acquisitionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquisitionTime(String value) {
        this.acquisitionTime = value;
    }

    /**
     * Gets the value of the acquisitionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquisitionDate() {
        return acquisitionDate;
    }

    /**
     * Sets the value of the acquisitionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquisitionDate(String value) {
        this.acquisitionDate = value;
    }

    /**
     * Gets the value of the cartNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCartNumber() {
        return cartNumber;
    }

    /**
     * Sets the value of the cartNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCartNumber(String value) {
        this.cartNumber = value;
    }

    /**
     * Gets the value of the acquisitionSoftwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquisitionSoftwareVersion() {
        return acquisitionSoftwareVersion;
    }

    /**
     * Sets the value of the acquisitionSoftwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquisitionSoftwareVersion(String value) {
        this.acquisitionSoftwareVersion = value;
    }

    /**
     * Gets the value of the analysisSoftwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalysisSoftwareVersion() {
        return analysisSoftwareVersion;
    }

    /**
     * Sets the value of the analysisSoftwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalysisSoftwareVersion(String value) {
        this.analysisSoftwareVersion = value;
    }

}
