//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 11:46:28 AM EDT 
//


package org.cvrgrid.gemuse.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}StmtFlag"/>
 *         &lt;element ref="{}StmtText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stmtFlag",
    "stmtText"
})
@XmlRootElement(name = "DiagnosisStatement")
public class DiagnosisStatement {

    @XmlElement(name = "StmtFlag", required = true)
    protected String stmtFlag;
    @XmlElement(name = "StmtText", required = true)
    protected String stmtText;

    /**
     * Gets the value of the stmtFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStmtFlag() {
        return stmtFlag;
    }

    /**
     * Sets the value of the stmtFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStmtFlag(String value) {
        this.stmtFlag = value;
    }

    /**
     * Gets the value of the stmtText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStmtText() {
        return stmtText;
    }

    /**
     * Sets the value of the stmtText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStmtText(String value) {
        this.stmtText = value;
    }

}
