//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 11:46:28 AM EDT 
//


package org.cvrgrid.gemuse.jaxb.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cvrgrid.gemuse.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataType_QNAME = new QName("", "DataType");
    private final static QName _LeadAmplitudeUnits_QNAME = new QName("", "LeadAmplitudeUnits");
    private final static QName _TAxis_QNAME = new QName("", "TAxis");
    private final static QName _DateofBirth_QNAME = new QName("", "DateofBirth");
    private final static QName _PatientFirstName_QNAME = new QName("", "PatientFirstName");
    private final static QName _SiteName_QNAME = new QName("", "SiteName");
    private final static QName _GlobalRR_QNAME = new QName("", "GlobalRR");
    private final static QName _PAxis_QNAME = new QName("", "PAxis");
    private final static QName _UnconfirmedReceivedTime_QNAME = new QName("", "UnconfirmedReceivedTime");
    private final static QName _TOffset_QNAME = new QName("", "TOffset");
    private final static QName _PatientAge_QNAME = new QName("", "PatientAge");
    private final static QName _SampleExponent_QNAME = new QName("", "SampleExponent");
    private final static QName _VentricularRate_QNAME = new QName("", "VentricularRate");
    private final static QName _LowPassFilter_QNAME = new QName("", "LowPassFilter");
    private final static QName _AcquisitionDate_QNAME = new QName("", "AcquisitionDate");
    private final static QName _Site_QNAME = new QName("", "Site");
    private final static QName _AdmitTime_QNAME = new QName("", "AdmitTime");
    private final static QName _Number_QNAME = new QName("", "Number");
    private final static QName _LeadID_QNAME = new QName("", "LeadID");
    private final static QName _MuseVersion_QNAME = new QName("", "MuseVersion");
    private final static QName _QTInterval_QNAME = new QName("", "QTInterval");
    private final static QName _ECGSampleBase_QNAME = new QName("", "ECGSampleBase");
    private final static QName _Race_QNAME = new QName("", "Race");
    private final static QName _AcquisitionDevice_QNAME = new QName("", "AcquisitionDevice");
    private final static QName _SampleBase_QNAME = new QName("", "SampleBase");
    private final static QName _RAxis_QNAME = new QName("", "RAxis");
    private final static QName _AcquisitionSoftwareVersion_QNAME = new QName("", "AcquisitionSoftwareVersion");
    private final static QName _LeadHighLimit_QNAME = new QName("", "LeadHighLimit");
    private final static QName _WaveformType_QNAME = new QName("", "WaveformType");
    private final static QName _LeadOffsetFirstSample_QNAME = new QName("", "LeadOffsetFirstSample");
    private final static QName _FirstSampleBaseline_QNAME = new QName("", "FirstSampleBaseline");
    private final static QName _Gender_QNAME = new QName("", "Gender");
    private final static QName _MeasurementMatrix_QNAME = new QName("", "MeasurementMatrix");
    private final static QName _StmtFlag_QNAME = new QName("", "StmtFlag");
    private final static QName _PRInterval_QNAME = new QName("", "PRInterval");
    private final static QName _Modality_QNAME = new QName("", "Modality");
    private final static QName _AcquisitionTime_QNAME = new QName("", "AcquisitionTime");
    private final static QName _QOffset_QNAME = new QName("", "QOffset");
    private final static QName _LeadTimeOffset_QNAME = new QName("", "LeadTimeOffset");
    private final static QName _NumberofLeads_QNAME = new QName("", "NumberofLeads");
    private final static QName _AnalysisSoftwareVersion_QNAME = new QName("", "AnalysisSoftwareVersion");
    private final static QName _CartNumber_QNAME = new QName("", "CartNumber");
    private final static QName _ACFilter_QNAME = new QName("", "ACFilter");
    private final static QName _WeightLBS_QNAME = new QName("", "WeightLBS");
    private final static QName _HeightIN_QNAME = new QName("", "HeightIN");
    private final static QName _LeadLowLimit_QNAME = new QName("", "LeadLowLimit");
    private final static QName _QRSDuration_QNAME = new QName("", "QRSDuration");
    private final static QName _Type_QNAME = new QName("", "Type");
    private final static QName _Time_QNAME = new QName("", "Time");
    private final static QName _SampleType_QNAME = new QName("", "SampleType");
    private final static QName _AtrialRate_QNAME = new QName("", "AtrialRate");
    private final static QName _QTCorrected_QNAME = new QName("", "QTCorrected");
    private final static QName _POffset_QNAME = new QName("", "POffset");
    private final static QName _WaveformStartTime_QNAME = new QName("", "WaveformStartTime");
    private final static QName _AgeUnits_QNAME = new QName("", "AgeUnits");
    private final static QName _StmtText_QNAME = new QName("", "StmtText");
    private final static QName _PatientLastName_QNAME = new QName("", "PatientLastName");
    private final static QName _LeadDataCRC32_QNAME = new QName("", "LeadDataCRC32");
    private final static QName _QRSCount_QNAME = new QName("", "QRSCount");
    private final static QName _POnset_QNAME = new QName("", "POnset");
    private final static QName _BaselineSway_QNAME = new QName("", "BaselineSway");
    private final static QName _WaveFormData_QNAME = new QName("", "WaveFormData");
    private final static QName _LeadSampleCountTotal_QNAME = new QName("", "LeadSampleCountTotal");
    private final static QName _HighPassFilter_QNAME = new QName("", "HighPassFilter");
    private final static QName _Location_QNAME = new QName("", "Location");
    private final static QName _ECGSampleExponent_QNAME = new QName("", "ECGSampleExponent");
    private final static QName _LeadOff_QNAME = new QName("", "LeadOff");
    private final static QName _LeadByteCountTotal_QNAME = new QName("", "LeadByteCountTotal");
    private final static QName _Priority_QNAME = new QName("", "Priority");
    private final static QName _Status_QNAME = new QName("", "Status");
    private final static QName _QOnset_QNAME = new QName("", "QOnset");
    private final static QName _LeadSampleSize_QNAME = new QName("", "LeadSampleSize");
    private final static QName _PatientID_QNAME = new QName("", "PatientID");
    private final static QName _LeadAmplitudeUnitsPerBit_QNAME = new QName("", "LeadAmplitudeUnitsPerBit");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cvrgrid.gemuse.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Diagnosis }
     * 
     */
    public Diagnosis createDiagnosis() {
        return new Diagnosis();
    }

    /**
     * Create an instance of {@link DiagnosisStatement }
     * 
     */
    public DiagnosisStatement createDiagnosisStatement() {
        return new DiagnosisStatement();
    }

    /**
     * Create an instance of {@link QRS }
     * 
     */
    public QRS createQRS() {
        return new QRS();
    }

    /**
     * Create an instance of {@link RegisteredName }
     * 
     */
    public RegisteredName createRegisteredName() {
        return new RegisteredName();
    }

    /**
     * Create an instance of {@link QRSTimesTypes }
     * 
     */
    public QRSTimesTypes createQRSTimesTypes() {
        return new QRSTimesTypes();
    }

    /**
     * Create an instance of {@link TestDemographics }
     * 
     */
    public TestDemographics createTestDemographics() {
        return new TestDemographics();
    }

    /**
     * Create an instance of {@link LeadData }
     * 
     */
    public LeadData createLeadData() {
        return new LeadData();
    }

    /**
     * Create an instance of {@link RestingECGMeasurements }
     * 
     */
    public RestingECGMeasurements createRestingECGMeasurements() {
        return new RestingECGMeasurements();
    }

    /**
     * Create an instance of {@link PatientDemographics }
     * 
     */
    public PatientDemographics createPatientDemographics() {
        return new PatientDemographics();
    }

    /**
     * Create an instance of {@link RestingECG }
     * 
     */
    public RestingECG createRestingECG() {
        return new RestingECG();
    }

    /**
     * Create an instance of {@link Waveform }
     * 
     */
    public Waveform createWaveform() {
        return new Waveform();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link MuseInfo }
     * 
     */
    public MuseInfo createMuseInfo() {
        return new MuseInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataType")
    public JAXBElement<String> createDataType(String value) {
        return new JAXBElement<String>(_DataType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadAmplitudeUnits")
    public JAXBElement<String> createLeadAmplitudeUnits(String value) {
        return new JAXBElement<String>(_LeadAmplitudeUnits_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TAxis")
    public JAXBElement<String> createTAxis(String value) {
        return new JAXBElement<String>(_TAxis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateofBirth")
    public JAXBElement<String> createDateofBirth(String value) {
        return new JAXBElement<String>(_DateofBirth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PatientFirstName")
    public JAXBElement<String> createPatientFirstName(String value) {
        return new JAXBElement<String>(_PatientFirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SiteName")
    public JAXBElement<String> createSiteName(String value) {
        return new JAXBElement<String>(_SiteName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GlobalRR")
    public JAXBElement<String> createGlobalRR(String value) {
        return new JAXBElement<String>(_GlobalRR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PAxis")
    public JAXBElement<String> createPAxis(String value) {
        return new JAXBElement<String>(_PAxis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UnconfirmedReceivedTime")
    public JAXBElement<String> createUnconfirmedReceivedTime(String value) {
        return new JAXBElement<String>(_UnconfirmedReceivedTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOffset")
    public JAXBElement<String> createTOffset(String value) {
        return new JAXBElement<String>(_TOffset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PatientAge")
    public JAXBElement<String> createPatientAge(String value) {
        return new JAXBElement<String>(_PatientAge_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SampleExponent")
    public JAXBElement<String> createSampleExponent(String value) {
        return new JAXBElement<String>(_SampleExponent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VentricularRate")
    public JAXBElement<String> createVentricularRate(String value) {
        return new JAXBElement<String>(_VentricularRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LowPassFilter")
    public JAXBElement<String> createLowPassFilter(String value) {
        return new JAXBElement<String>(_LowPassFilter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AcquisitionDate")
    public JAXBElement<String> createAcquisitionDate(String value) {
        return new JAXBElement<String>(_AcquisitionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Site")
    public JAXBElement<String> createSite(String value) {
        return new JAXBElement<String>(_Site_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AdmitTime")
    public JAXBElement<String> createAdmitTime(String value) {
        return new JAXBElement<String>(_AdmitTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Number")
    public JAXBElement<String> createNumber(String value) {
        return new JAXBElement<String>(_Number_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadID")
    public JAXBElement<String> createLeadID(String value) {
        return new JAXBElement<String>(_LeadID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MuseVersion")
    public JAXBElement<String> createMuseVersion(String value) {
        return new JAXBElement<String>(_MuseVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QTInterval")
    public JAXBElement<String> createQTInterval(String value) {
        return new JAXBElement<String>(_QTInterval_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ECGSampleBase")
    public JAXBElement<String> createECGSampleBase(String value) {
        return new JAXBElement<String>(_ECGSampleBase_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Race")
    public JAXBElement<String> createRace(String value) {
        return new JAXBElement<String>(_Race_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AcquisitionDevice")
    public JAXBElement<String> createAcquisitionDevice(String value) {
        return new JAXBElement<String>(_AcquisitionDevice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SampleBase")
    public JAXBElement<String> createSampleBase(String value) {
        return new JAXBElement<String>(_SampleBase_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RAxis")
    public JAXBElement<String> createRAxis(String value) {
        return new JAXBElement<String>(_RAxis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AcquisitionSoftwareVersion")
    public JAXBElement<String> createAcquisitionSoftwareVersion(String value) {
        return new JAXBElement<String>(_AcquisitionSoftwareVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadHighLimit")
    public JAXBElement<String> createLeadHighLimit(String value) {
        return new JAXBElement<String>(_LeadHighLimit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WaveformType")
    public JAXBElement<String> createWaveformType(String value) {
        return new JAXBElement<String>(_WaveformType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadOffsetFirstSample")
    public JAXBElement<String> createLeadOffsetFirstSample(String value) {
        return new JAXBElement<String>(_LeadOffsetFirstSample_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FirstSampleBaseline")
    public JAXBElement<String> createFirstSampleBaseline(String value) {
        return new JAXBElement<String>(_FirstSampleBaseline_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Gender")
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MeasurementMatrix")
    public JAXBElement<String> createMeasurementMatrix(String value) {
        return new JAXBElement<String>(_MeasurementMatrix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StmtFlag")
    public JAXBElement<String> createStmtFlag(String value) {
        return new JAXBElement<String>(_StmtFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRInterval")
    public JAXBElement<String> createPRInterval(String value) {
        return new JAXBElement<String>(_PRInterval_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Modality")
    public JAXBElement<String> createModality(String value) {
        return new JAXBElement<String>(_Modality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AcquisitionTime")
    public JAXBElement<String> createAcquisitionTime(String value) {
        return new JAXBElement<String>(_AcquisitionTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QOffset")
    public JAXBElement<String> createQOffset(String value) {
        return new JAXBElement<String>(_QOffset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadTimeOffset")
    public JAXBElement<String> createLeadTimeOffset(String value) {
        return new JAXBElement<String>(_LeadTimeOffset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumberofLeads")
    public JAXBElement<String> createNumberofLeads(String value) {
        return new JAXBElement<String>(_NumberofLeads_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AnalysisSoftwareVersion")
    public JAXBElement<String> createAnalysisSoftwareVersion(String value) {
        return new JAXBElement<String>(_AnalysisSoftwareVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CartNumber")
    public JAXBElement<String> createCartNumber(String value) {
        return new JAXBElement<String>(_CartNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACFilter")
    public JAXBElement<String> createACFilter(String value) {
        return new JAXBElement<String>(_ACFilter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WeightLBS")
    public JAXBElement<String> createWeightLBS(String value) {
        return new JAXBElement<String>(_WeightLBS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HeightIN")
    public JAXBElement<String> createHeightIN(String value) {
        return new JAXBElement<String>(_HeightIN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadLowLimit")
    public JAXBElement<String> createLeadLowLimit(String value) {
        return new JAXBElement<String>(_LeadLowLimit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QRSDuration")
    public JAXBElement<String> createQRSDuration(String value) {
        return new JAXBElement<String>(_QRSDuration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Time")
    public JAXBElement<String> createTime(String value) {
        return new JAXBElement<String>(_Time_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SampleType")
    public JAXBElement<String> createSampleType(String value) {
        return new JAXBElement<String>(_SampleType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AtrialRate")
    public JAXBElement<String> createAtrialRate(String value) {
        return new JAXBElement<String>(_AtrialRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QTCorrected")
    public JAXBElement<String> createQTCorrected(String value) {
        return new JAXBElement<String>(_QTCorrected_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "POffset")
    public JAXBElement<String> createPOffset(String value) {
        return new JAXBElement<String>(_POffset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WaveformStartTime")
    public JAXBElement<String> createWaveformStartTime(String value) {
        return new JAXBElement<String>(_WaveformStartTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AgeUnits")
    public JAXBElement<String> createAgeUnits(String value) {
        return new JAXBElement<String>(_AgeUnits_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StmtText")
    public JAXBElement<String> createStmtText(String value) {
        return new JAXBElement<String>(_StmtText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PatientLastName")
    public JAXBElement<String> createPatientLastName(String value) {
        return new JAXBElement<String>(_PatientLastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadDataCRC32")
    public JAXBElement<String> createLeadDataCRC32(String value) {
        return new JAXBElement<String>(_LeadDataCRC32_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QRSCount")
    public JAXBElement<String> createQRSCount(String value) {
        return new JAXBElement<String>(_QRSCount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "POnset")
    public JAXBElement<String> createPOnset(String value) {
        return new JAXBElement<String>(_POnset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BaselineSway")
    public JAXBElement<String> createBaselineSway(String value) {
        return new JAXBElement<String>(_BaselineSway_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WaveFormData")
    public JAXBElement<String> createWaveFormData(String value) {
        return new JAXBElement<String>(_WaveFormData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadSampleCountTotal")
    public JAXBElement<String> createLeadSampleCountTotal(String value) {
        return new JAXBElement<String>(_LeadSampleCountTotal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HighPassFilter")
    public JAXBElement<String> createHighPassFilter(String value) {
        return new JAXBElement<String>(_HighPassFilter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Location")
    public JAXBElement<String> createLocation(String value) {
        return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ECGSampleExponent")
    public JAXBElement<String> createECGSampleExponent(String value) {
        return new JAXBElement<String>(_ECGSampleExponent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadOff")
    public JAXBElement<String> createLeadOff(String value) {
        return new JAXBElement<String>(_LeadOff_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadByteCountTotal")
    public JAXBElement<String> createLeadByteCountTotal(String value) {
        return new JAXBElement<String>(_LeadByteCountTotal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Priority")
    public JAXBElement<String> createPriority(String value) {
        return new JAXBElement<String>(_Priority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QOnset")
    public JAXBElement<String> createQOnset(String value) {
        return new JAXBElement<String>(_QOnset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadSampleSize")
    public JAXBElement<String> createLeadSampleSize(String value) {
        return new JAXBElement<String>(_LeadSampleSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PatientID")
    public JAXBElement<String> createPatientID(String value) {
        return new JAXBElement<String>(_PatientID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeadAmplitudeUnitsPerBit")
    public JAXBElement<String> createLeadAmplitudeUnitsPerBit(String value) {
        return new JAXBElement<String>(_LeadAmplitudeUnitsPerBit_QNAME, String.class, null, value);
    }

}
