//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 11:46:28 AM EDT 
//


package org.cvrgrid.gemuse.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}VentricularRate"/>
 *         &lt;element ref="{}AtrialRate"/>
 *         &lt;element ref="{}PRInterval"/>
 *         &lt;element ref="{}QRSDuration"/>
 *         &lt;element ref="{}QTInterval"/>
 *         &lt;element ref="{}QTCorrected"/>
 *         &lt;element ref="{}PAxis"/>
 *         &lt;element ref="{}RAxis"/>
 *         &lt;element ref="{}TAxis"/>
 *         &lt;element ref="{}QRSCount"/>
 *         &lt;element ref="{}QOnset"/>
 *         &lt;element ref="{}QOffset"/>
 *         &lt;element ref="{}POnset"/>
 *         &lt;element ref="{}POffset"/>
 *         &lt;element ref="{}TOffset"/>
 *         &lt;element ref="{}ECGSampleBase"/>
 *         &lt;element ref="{}ECGSampleExponent"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ventricularRate",
    "atrialRate",
    "prInterval",
    "qrsDuration",
    "qtInterval",
    "qtCorrected",
    "pAxis",
    "rAxis",
    "tAxis",
    "qrsCount",
    "qOnset",
    "qOffset",
    "pOnset",
    "pOffset",
    "tOffset",
    "ecgSampleBase",
    "ecgSampleExponent"
})
@XmlRootElement(name = "RestingECGMeasurements")
public class RestingECGMeasurements {

    @XmlElement(name = "VentricularRate", required = true)
    protected String ventricularRate;
    @XmlElement(name = "AtrialRate", required = true)
    protected String atrialRate;
    @XmlElement(name = "PRInterval", required = true)
    protected String prInterval;
    @XmlElement(name = "QRSDuration", required = true)
    protected String qrsDuration;
    @XmlElement(name = "QTInterval", required = true)
    protected String qtInterval;
    @XmlElement(name = "QTCorrected", required = true)
    protected String qtCorrected;
    @XmlElement(name = "PAxis", required = true)
    protected String pAxis;
    @XmlElement(name = "RAxis", required = true)
    protected String rAxis;
    @XmlElement(name = "TAxis", required = true)
    protected String tAxis;
    @XmlElement(name = "QRSCount", required = true)
    protected String qrsCount;
    @XmlElement(name = "QOnset", required = true)
    protected String qOnset;
    @XmlElement(name = "QOffset", required = true)
    protected String qOffset;
    @XmlElement(name = "POnset", required = true)
    protected String pOnset;
    @XmlElement(name = "POffset", required = true)
    protected String pOffset;
    @XmlElement(name = "TOffset", required = true)
    protected String tOffset;
    @XmlElement(name = "ECGSampleBase", required = true)
    protected String ecgSampleBase;
    @XmlElement(name = "ECGSampleExponent", required = true)
    protected String ecgSampleExponent;

    /**
     * Gets the value of the ventricularRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVentricularRate() {
        return ventricularRate;
    }

    /**
     * Sets the value of the ventricularRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVentricularRate(String value) {
        this.ventricularRate = value;
    }

    /**
     * Gets the value of the atrialRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtrialRate() {
        return atrialRate;
    }

    /**
     * Sets the value of the atrialRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtrialRate(String value) {
        this.atrialRate = value;
    }

    /**
     * Gets the value of the prInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRInterval() {
        return prInterval;
    }

    /**
     * Sets the value of the prInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRInterval(String value) {
        this.prInterval = value;
    }

    /**
     * Gets the value of the qrsDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQRSDuration() {
        return qrsDuration;
    }

    /**
     * Sets the value of the qrsDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQRSDuration(String value) {
        this.qrsDuration = value;
    }

    /**
     * Gets the value of the qtInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQTInterval() {
        return qtInterval;
    }

    /**
     * Sets the value of the qtInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQTInterval(String value) {
        this.qtInterval = value;
    }

    /**
     * Gets the value of the qtCorrected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQTCorrected() {
        return qtCorrected;
    }

    /**
     * Sets the value of the qtCorrected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQTCorrected(String value) {
        this.qtCorrected = value;
    }

    /**
     * Gets the value of the pAxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAxis() {
        return pAxis;
    }

    /**
     * Sets the value of the pAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAxis(String value) {
        this.pAxis = value;
    }

    /**
     * Gets the value of the rAxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRAxis() {
        return rAxis;
    }

    /**
     * Sets the value of the rAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRAxis(String value) {
        this.rAxis = value;
    }

    /**
     * Gets the value of the tAxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAxis() {
        return tAxis;
    }

    /**
     * Sets the value of the tAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAxis(String value) {
        this.tAxis = value;
    }

    /**
     * Gets the value of the qrsCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQRSCount() {
        return qrsCount;
    }

    /**
     * Sets the value of the qrsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQRSCount(String value) {
        this.qrsCount = value;
    }

    /**
     * Gets the value of the qOnset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQOnset() {
        return qOnset;
    }

    /**
     * Sets the value of the qOnset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQOnset(String value) {
        this.qOnset = value;
    }

    /**
     * Gets the value of the qOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQOffset() {
        return qOffset;
    }

    /**
     * Sets the value of the qOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQOffset(String value) {
        this.qOffset = value;
    }

    /**
     * Gets the value of the pOnset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOnset() {
        return pOnset;
    }

    /**
     * Sets the value of the pOnset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOnset(String value) {
        this.pOnset = value;
    }

    /**
     * Gets the value of the pOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOffset() {
        return pOffset;
    }

    /**
     * Sets the value of the pOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOffset(String value) {
        this.pOffset = value;
    }

    /**
     * Gets the value of the tOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOffset() {
        return tOffset;
    }

    /**
     * Sets the value of the tOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOffset(String value) {
        this.tOffset = value;
    }

    /**
     * Gets the value of the ecgSampleBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECGSampleBase() {
        return ecgSampleBase;
    }

    /**
     * Sets the value of the ecgSampleBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECGSampleBase(String value) {
        this.ecgSampleBase = value;
    }

    /**
     * Gets the value of the ecgSampleExponent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECGSampleExponent() {
        return ecgSampleExponent;
    }

    /**
     * Sets the value of the ecgSampleExponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECGSampleExponent(String value) {
        this.ecgSampleExponent = value;
    }

}
