//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 11:46:28 AM EDT 
//


package org.cvrgrid.gemuse.jaxb.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}WaveformType"/>
 *         &lt;element ref="{}WaveformStartTime"/>
 *         &lt;element ref="{}NumberofLeads"/>
 *         &lt;element ref="{}SampleType"/>
 *         &lt;element ref="{}SampleBase"/>
 *         &lt;element ref="{}SampleExponent"/>
 *         &lt;element ref="{}HighPassFilter"/>
 *         &lt;element ref="{}LowPassFilter"/>
 *         &lt;element ref="{}ACFilter"/>
 *         &lt;element ref="{}LeadData" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "waveformType",
    "waveformStartTime",
    "numberofLeads",
    "sampleType",
    "sampleBase",
    "sampleExponent",
    "highPassFilter",
    "lowPassFilter",
    "acFilter",
    "leadData"
})
@XmlRootElement(name = "Waveform")
public class Waveform {

    @XmlElement(name = "WaveformType", required = true)
    protected String waveformType;
    @XmlElement(name = "WaveformStartTime", required = true)
    protected String waveformStartTime;
    @XmlElement(name = "NumberofLeads", required = true)
    protected String numberofLeads;
    @XmlElement(name = "SampleType", required = true)
    protected String sampleType;
    @XmlElement(name = "SampleBase", required = true)
    protected String sampleBase;
    @XmlElement(name = "SampleExponent", required = true)
    protected String sampleExponent;
    @XmlElement(name = "HighPassFilter", required = true)
    protected String highPassFilter;
    @XmlElement(name = "LowPassFilter", required = true)
    protected String lowPassFilter;
    @XmlElement(name = "ACFilter", required = true)
    protected String acFilter;
    @XmlElement(name = "LeadData", required = true)
    protected List<LeadData> leadData;

    /**
     * Gets the value of the waveformType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaveformType() {
        return waveformType;
    }

    /**
     * Sets the value of the waveformType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaveformType(String value) {
        this.waveformType = value;
    }

    /**
     * Gets the value of the waveformStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaveformStartTime() {
        return waveformStartTime;
    }

    /**
     * Sets the value of the waveformStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaveformStartTime(String value) {
        this.waveformStartTime = value;
    }

    /**
     * Gets the value of the numberofLeads property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberofLeads() {
        return numberofLeads;
    }

    /**
     * Sets the value of the numberofLeads property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberofLeads(String value) {
        this.numberofLeads = value;
    }

    /**
     * Gets the value of the sampleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleType() {
        return sampleType;
    }

    /**
     * Sets the value of the sampleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleType(String value) {
        this.sampleType = value;
    }

    /**
     * Gets the value of the sampleBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleBase() {
        return sampleBase;
    }

    /**
     * Sets the value of the sampleBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleBase(String value) {
        this.sampleBase = value;
    }

    /**
     * Gets the value of the sampleExponent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleExponent() {
        return sampleExponent;
    }

    /**
     * Sets the value of the sampleExponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleExponent(String value) {
        this.sampleExponent = value;
    }

    /**
     * Gets the value of the highPassFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighPassFilter() {
        return highPassFilter;
    }

    /**
     * Sets the value of the highPassFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighPassFilter(String value) {
        this.highPassFilter = value;
    }

    /**
     * Gets the value of the lowPassFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowPassFilter() {
        return lowPassFilter;
    }

    /**
     * Sets the value of the lowPassFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowPassFilter(String value) {
        this.lowPassFilter = value;
    }

    /**
     * Gets the value of the acFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACFilter() {
        return acFilter;
    }

    /**
     * Sets the value of the acFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACFilter(String value) {
        this.acFilter = value;
    }

    /**
     * Gets the value of the leadData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leadData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeadData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LeadData }
     * 
     * 
     */
    public List<LeadData> getLeadData() {
        if (leadData == null) {
            leadData = new ArrayList<LeadData>();
        }
        return this.leadData;
    }

}
